### ISSUE TITLE
Backbone Materials - Suggested Long-term Revision

### ISSUE THREAD

**Issue by CheezItMan** [Ada-Developers-Academy/textbook-curriculum#142]
Assuming we stick with Backbone for a cohort or two, I'd like to suggest we revise the materials to separate reference material & Live-Code Material.

Also I'd suggest pulling Underscore Templates out and doing a bit more with them before we get to Backbone, maybe with AJAX.

Example:
02-Backbone-views.md  - reference material for Backbone development
02a-Backbone-views-Livecode.md  - Walkthrough instructions and code.

**Comment by droberts-ada** [comment]
This is an interesting idea - the live-code / walkthrough we've got for backbone is huge, and dominates the material.

Do you envision leaving the live code pretty much as is, and creating the reference document from scratch? Or would we remove large chunks from the live code?

How do you see the reference material being used?

**Comment by CheezItMan** [comment]
Reference material would be useful for someone with, "How does ... work?" type of question.  It would be reference material for students to look up individual functionality and functions.  The live code is great for following along a tutorial, but I imagine less useful for questions as the build apps. 

I would think we could leave the live code pretty much as-is and pulling and editing specific examples for reference material.

**Comment by droberts-ada** [comment]
That sounds like a lot more work than just telling them to google it :P

**Comment by CheezItMan** [comment]
True, but since Backbone is a library there are an awful lot of different ways of doing things, and less explaining concepts like el vs $el, routers etc.

It may be too much then.

**Comment by droberts-ada** [comment]
Yeah, having an Ada way to do things would definitely be helpful. At the very least we can provide links to stackoverflow / tutorial sites / the doc, and contextualize complex explanations in terms of the live code or the projects.
