### ISSUE TITLE
Ruby/Intro to Object Types: Hashes do have fixed order

### ISSUE THREAD

**Issue by Hamled** [Ada-Developers-Academy/textbook-curriculum#174]
We should remove the comment about hashes not having a fixed order. Since Ruby 1.9 hashes retain their insertion order.

**Comment by sudocrystal** [comment]
Whoa - I just learned something new. I wonder why insertion order is now retained and what that does to the efficiency of a Ruby Hash.

**Comment by Hamled** [comment]
@sudocrystal There's a bit of detail in [this post](https://www.igvita.com/2009/02/04/ruby-19-internals-ordered-hash/).

They're retaining insertion order as an explicit feature (trying to hold to a principle of "least surprise"), and using a circular doubly linked list to hold the pairs. Also apparently they're at least as fast as the original implementation.
